### GET Jogos
GET http://localhost:8080/api/v1/jogos
Content-Type: application/json

### POST jogos
POST http://localhost:8080/api/v1/jogos
Content-Type: application/json

{
  "categoria_id": 3,
  "data_lancamento": "2025-09-11",
  "id": 0,
  "plataforma_id": "2",
  "descricao": "bom",
  "nome": "thelastofus"
}

### PUT Jogos
PUT http://localhost:8080/api/v1/jogos/1
Content-Type: application/json

{
  "categoria_id": 4,
  "data_lancamento": "2025-09-21",
  "id": 0,
  "plataforma_id": "3",
  "descricao": "flopou",
  "nome": "csgo"
}

### DELETE Jogos
DELETE http://localhost:8080/api/v1/jogos/1
Content-Type: application/json

####### Categoria #######

# GET categoria
GET http://localhost:8080/api/v1/categorias
Content-Type: application/json

POST http://localhost:8080/api/v1/categorias
Content-Type: application/json

{
  "id": 0,
  "nome": "Ação"
}


PUT http://localhost:8080/api/v1/categorias/1
Content-Type: application/json

{
  "id": 0,
  "nome": "Aventura"
}

DELETE http://localhost:8080/api/v1/categorias/1
Content-Type: application/json
