### GET Jogos
GET http://localhost:8080/api/v1/jogos
Content-Type: application/json

### POST jogos
POST http://localhost:8080/api/v1/jogos
Content-Type: application/json

{
  "categoria": { "id": 1 },
  "dataLancamento": "2025-09-11",
  "plataforma": { "id": 2 },
  "descricao": "bom",
  "nome": "ligadaslendas"
}


### PUT Jogos
PUT http://localhost:8080/api/v1/jogos/1
Content-Type: application/json

{
  "categoria": { "id": 1 },
  "dataLancamento": "2025-09-21",
  "plataforma": { "id": 1 },
  "descricao": "ok",
  "nome": "csgo"
}

### DELETE Jogos
DELETE http://localhost:8080/api/v1/jogos/2
Content-Type: application/json

####### Categoria #######

### GET categoria
GET http://localhost:8080/api/v1/categorias
Content-Type: application/json
### POST categoria
POST http://localhost:8080/api/v1/categorias
Content-Type: application/json

{
  "nome": "Ação"
}

### PUT categoria
PUT http://localhost:8080/api/v1/categorias/1
Content-Type: application/json

{
  "nome": "Terror"
}

### DELETE categoria
DELETE http://localhost:8080/api/v1/categorias/1
Content-Type: application/json

####### Plataforma #######

### GET plataforma
GET http://localhost:8080/api/v1/plataformas
Content-Type: application/json
### POST plataforma
POST http://localhost:8080/api/v1/plataformas
Content-Type: application/json

{
  "nome": "Playstation 5"
}

### PUT plataforma
PUT http://localhost:8080/api/v1/plataformas/1
Content-Type: application/json

{
  "nome": "Xbox Series X"
}

### DELETE plataforma
DELETE http://localhost:8080/api/v1/plataformas/1
Content-Type: application/json

####### Usuário #######

### GET usuario
GET http://localhost:8080/api/v1/usuarios
Content-Type: application/json
### POST usuario
POST http://localhost:8080/api/v1/usuarios
Content-Type: application/json

{
  "nome": "Fulano da Silva",
  "email": "fulano@email.com",
  "senha": "123456",
  "dataNascimento": "1995-08-20"
}

### PUT usuario
PUT http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json

{
  "nome": "Ciclano da Silva",
  "email": "clicano@email.com",
  "senha": "54321",
  "dataNascimento": "1995-08-21"
}

### DELETE usuario
DELETE http://localhost:8080/api/v1/usuarios/1
Content-Type: application/json